version: '2'
services:
  app: 
    container_name: "toG3-team2-app"
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes: 
      - ".:/app"
      - bundle:/usr/local/bundle 
    ports: 
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_NAME: toG3-team2-app
      DB_PASSWORD: password
      DB_HOST: db
      EDITOR: vim

  db: 
    container_name: "toG3-team2-db"
    image: mysql:8.0.36
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: toG3-team2-app
      MYSQL_USER: team2
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  # redis:
  #   container_name: "toG3-team2-redis"
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - "./data/redis:/data"
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio123"
    command: ["minio", "server", "/data", "--console-address", ":9001"]
    volumes:
      - ./storage/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - '8025:8025'
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp
volumes:
  maildir:
    name: app_maildir
  bundle:
  mysql:
